version: '3.5'
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    image: resto-react
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./:/src
    working_dir: /src
    networks:
      - resto-network

networks:
  resto-network:
    external: true