version: '3.8'
services:
  django:
    extends:
      file: ./django_api/docker-compose.yaml
      service: django
    networks:
      - resto-network

  react:
    extends:
      file: ./frontend/docker-compose.yaml
      service: react
    networks:
      - resto-network

networks:
  resto-network:
    driver: bridge