version: '3.8'
services:
  django:
    build:
      context: ./django_api
      dockerfile: ./django_api/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - resto-network

  react:
    build:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
    command: npm start
    ports:
      - "8009:3000"
    tty: true
    volumes:
      - ./:/src
    depends_on:
      - django
    networks:
      - resto-network

networks:
  resto-network:
    driver: bridge
