version: '3'
services:
  django:
    build:
      context: ./django_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./django:/usr/src/app

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - django