# Generated by Django 4.2 on 2023-04-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto_app', '0006_dish_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
