# Generated by Django 4.2 on 2023-04-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto_app', '0007_employee_image_jobopening_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='recommended',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
